version: "3.7"
services:
  mysql-server:
    image: test-mysql
    restart: always
    networks:
      - w3snet
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    networks:
      - w3snet
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
volumes:
  mysql-data:

networks:
  w3snet:
    driver: bridge